Page({
	data:{
		arr:[{
			src:"https://www.zhonghuiqh.com/invite/images/img1.jpg"
		},
		{
			src:"https://www.zhonghuiqh.com/invite/images/img2.jpg"
		},
		{
			src:"https://www.zhonghuiqh.com/invite/images/img3.jpg"
		}]
	}
})
